// Auto-generated from 'quest pool.xlsx'. Do not edit by hand.
window.QUEST_POOL = {
  "outside": {
    "color": "outside",
    "subcategories": [
      {
        "key": "discovery",
        "label": "Discovery",
        "shape": "discovery",
        "quests": [
          "Visit a nearby town",
          "Visit a new street",
          "Explore a nearby spot",
          "Walk a different route",
          "Visit your next bus stop",
          "Try a new café",
          "Explore a new neighborhood",
          "Eat at a place with no reviews checked",
          "Go somewhere you usually avoid",
          "Take a stop you never take",
          "Sit somewhere you’ve never sat",
          "Buy a snack you’ve never tried",
          "Find a hidden alley",
          "Follow a road you ignore",
          "Take the long way home",
          "Walk until something surprises you",
          "Walk with no destination",
          "Find a quiet spot in the city",
          "Explore somewhere touristy",
          "Find a street mural",
          "Visit a small bridge",
          "Find a unique mailbox",
          "Discover a hidden path",
          "Visit a local monument",
          "Visit a public square",
          "Explore a new block",
          "Explore a side street",
          "Find a historical plaque",
          "Visit a viewpoint",
          "Photograph an interesting shadow",
          "Explore near a river",
          "Find a scenic photo spot",
          "Visit a playground",
          "Visit a local landmark",
          "Walk around a church",
          "Discover a quiet corner",
          "Explore a trail",
          "Visit a garden",
          "Visit a place at sunrise",
          "Explore a nearby field",
          "Visit a place you've never noticed"
        ]
      },
      {
        "key": "action",
        "label": "Action",
        "shape": "action",
        "quests": [
          "Watch the sunset",
          "Sit in a park for 10 minutes",
          "Walk 5,000 steps",
          "Ride a bike",
          "Watch clouds for 5 minutes",
          "Visit a local shop",
          "Sit somewhere quiet",
          "Pick up litter (1 item)",
          "Smell a flower",
          "Attend a live music gig",
          "visit the library",
          "Go to an exhibition",
          "Go to a local market",
          "*Touch grass*",
          "Try Bird watching",
          "Meditate Outside",
          "Go to the beach",
          "Go Stargazing",
          "Visit a Museum",
          "Sketch in nature",
          "Hike a local trail",
          "Go for a jog",
          "Read 10 pages of a book outside",
          "Have a picnic for one",
          "Paint a landscape",
          "Do some outdoor Yoga",
          "Take a walk",
          "Make outdoor crafts",
          "Follow an ant trail",
          "Build a fairy house",
          "Make a flower crown",
          "Jump in a puddle",
          "Roll down a hill",
          "Walk 1 km",
          "Do 20 jumping jacks outside",
          "Sit by water for 5 minutes",
          "Watch a sunrise",
          "Walk barefoot on grass",
          "Take a nature photo",
          "Spend 10 minutes outdoors",
          "Climb a hill",
          "Watch birds for 5 minutes",
          "Do a short jog",
          "Have a snack outside",
          "Stretch in a park",
          "Walk without headphones",
          "Take a photo of the sky",
          "Visit a green space",
          "Watch the wind in trees",
          "Walk a loop around your neighborhood"
        ]
      },
      {
        "key": "scavenger_hunt",
        "label": "Scavenger Hunt",
        "shape": "scavenger_hunt",
        "quests": [
          "Find an interesting car",
          "Find an interesting tree",
          "Take a picture of something beautiful",
          "Take a city photo",
          "Find a four-leaf clover",
          "Find a bug",
          "Find a wild flower",
          "Find a printed advert about anything",
          "Find a bird",
          "Take a picture of a wild animal",
          "Find a funky mushroom",
          "Find an interesting leaf",
          "Find a sword-like stick",
          "Find a beetle",
          "Find an intriguing structure",
          "Find a colorful bird",
          "Find an interesting rock formation",
          "Find a fish",
          "Find a water bird",
          "Find a pretty rock",
          "Find a trashcan",
          "Find the biggest structure in your city",
          "Find a stop sign",
          "Find something blue",
          "Find something purple",
          "Find something yellow",
          "Find something pink",
          "Find a statue",
          "Find a flag",
          "Find a vehicle that's not a car",
          "Find a fountain",
          "Find beautiful architecture",
          "Find an emoji outside",
          "Find a spiderweb",
          "Find a cat",
          "Find a dog",
          "Find a yellow car",
          "Find a red bicycle",
          "Find a heart shape",
          "Find a blue door",
          "Find a reflection",
          "Find a bird",
          "Find a funny sign",
          "Find a yellow flower",
          "Find something round",
          "Find a leaf larger than your hand",
          "Find unusual architecture",
          "Find a building with a clock",
          "Find a shadow pattern",
          "Find something striped",
          "Find a unique bench",
          "Find a building older than 50 years",
          "Find a colorful door",
          "Find an old building",
          "Find a street mural",
          "Find a unique mailbox"
        ]
      }
    ]
  },
  "indoor": {
    "color": "indoor",
    "subcategories": [
      {
        "key": "tasks",
        "label": "Tasks",
        "shape": "tasks",
        "quests": [
          "Take out the trash",
          "Clean your desk",
          "Make your bed neatly",
          "Organize one drawer",
          "Water your plants",
          "Clean your bathroom sink",
          "Sort your clothes pile",
          "Do the dishes",
          "Deep clean the refrigerator",
          "Clean the oven",
          "Go grocery shopping",
          "Vacuum a room",
          "Clean your shoes",
          "Scrub the toilet",
          "Dust one room",
          "Do one task you've been procrastinating",
          "Do the laundry",
          "Reorganize your closet",
          "Make a grocery list",
          "Clean out your junk drawer",
          "Make a to-do list",
          "Organize your stationery",
          "Sew a loose button",
          "Fold five items of clothing",
          "Wipe a mirror",
          "Clean a shelf",
          "Organize a backpack",
          "Throw away old receipts",
          "Dust one surface",
          "Refill a water bottle",
          "Tidy a corner of a room",
          "Clean a keyboard",
          "Sort a small drawer",
          "Put away ten items",
          "Vacuum one room",
          "Clean a window",
          "Organize cables",
          "Wash a reusable bottle",
          "Prepare tomorrow's outfit",
          "Clean a doorknob",
          "Sort a stack of papers",
          "Declutter for 10 minutes",
          "Sweep a floor",
          "Rearrange a shelf",
          "Clean a light switch",
          "find something to sell"
        ]
      },
      {
        "key": "diy",
        "label": "DIY",
        "shape": "creative",
        "quests": [
          "Bake a cake",
          "Draw a picture of an animal",
          "Decorate your workspace",
          "Bake something small",
          "Create a cozy space",
          "Fix something broken",
          "Write a short poem",
          "Try origami",
          "Make a paper star",
          "Paint something tiny",
          "Learn one card trick",
          "Make homemade hot chocolate",
          "Create a playlsit",
          "Make a paper airplane",
          "Create a tiny sculpture",
          "Make fridge art",
          "Create a moodboard",
          "Create a paper flower",
          "Bake some cookies",
          "Learn to juggle",
          "Repurpose old clothes",
          "Learn a simple dance",
          "Make a collage",
          "Paint with coffee or tea",
          "Make a small snack for yourself",
          "Draw a short comic",
          "Decorate a mug",
          "Learn a magic trick",
          "Draw with your non-dominant hand",
          "Craft a photo frame",
          "Write a short story",
          "Make a paper airplane",
          "Create a bookmark",
          "Draw a landscape",
          "Paint a simple object",
          "Make a greeting card",
          "Decorate a notebook",
          "Build something from cardboard",
          "Create a collage",
          "Sketch your room",
          "Make a paper snowflake",
          "Customize a mug",
          "Write a haiku",
          "Paint a rock",
          "Make a keychain",
          "make a bucketlist",
          "build a blanket fort"
        ]
      },
      {
        "key": "selfcare",
        "label": "Selfcare",
        "shape": "selfcare",
        "quests": [
          "Light a candle and relax",
          "Read 5 pages of a book",
          "Do a 10-min stretch",
          "Make a cup of tea",
          "Cook your favorite food",
          "Do 10 push-ups",
          "Take a relaxing bath",
          "Take a shower",
          "Practice yoga",
          "Drink a cup of tea",
          "Meditate for at least 5 minutes",
          "Do 10 Squats",
          "Write one diary entry",
          "Watch an episode of your favorite show",
          "Take a nap",
          "Do 10 Jumping Jacks",
          "Massage your shoulders",
          "Practice deep breathing",
          "Listen to your favorite song",
          "Practice your hobby",
          "Tidy your sleeping area",
          "Spend time with your pet",
          "Build a pillow fort",
          "Take an everything shower",
          "Research a topic you're interested in",
          "Drink a glass of water",
          "Meditate for 5 minutes",
          "Take a short nap",
          "Listen to calming music",
          "Write down three good things",
          "Eat a piece of fruit",
          "Take a screen break",
          "Practice deep breathing",
          "Moisturize your hands",
          "Sit quietly for 5 minutes",
          "Open a window for fresh air",
          "Make a simple healthy meal",
          "Do a gratitude exercise",
          "Spend 10 minutes stretching",
          "Enjoy a healthy snack",
          "Journal for 5 minutes",
          "try a new recipe",
          "eat a vegetarian meal",
          "make a list of 3 things you like about yourself",
          "try something you usually don't like",
          "try something you never buy"
        ]
      }
    ]
  },
  "social": {
    "color": "social",
    "subcategories": [
      {
        "key": "game",
        "label": "Game",
        "shape": "game",
        "quests": [
          "Play rock paper scissors",
          "Play Tic-Tac-Toe",
          "Play Hide and Seek",
          "Play Tag with someone",
          "Play Imposter Game",
          "Play a videogame with someone",
          "Play Poker",
          "Play a board game with someone",
          "Play a card game with someone",
          "Play Chess with someone",
          "Play Truth or Dare with someone",
          "Play a game of Guess Who",
          "Play a game of telephone",
          "Play catch",
          "Play 'Name That Song' with someone",
          "Play charades with someone",
          "Play 'I spy' with someone",
          "play 'would you rather' with someone",
          "Play Hangman with someone",
          "Play 'Two Truths and a Lie' with someone",
          "Play 'Hot potato' with someone",
          "Play 'Never have I ever' with someone",
          "Play Bingo with someone",
          "Play charades",
          "Play a memory game with someone",
          "Play 'Musical Chairs' with someone",
          "Play '20 Questions' with someone",
          "Play 'Pictionary' with someone",
          "Play 'Simon says' with someone",
          "Play a guessing game together",
          "Play table tennis together",
          "Play badminton together",
          "Play a word association game with someone",
          "Play a trivia round together",
          "Play a dice game with someone",
          "Play checkers against someone",
          "Play dodgeball with someone",
          "Build a card tower together",
          "Invent a new game with someone",
          "Race paper airplanes against someone"
        ]
      },
      {
        "key": "activity",
        "label": "Activity",
        "shape": "activity",
        "quests": [
          "Draw a portrait of another person",
          "Take a walk in nature with someone",
          "Invite someone for coffee",
          "Watch a movie with someone",
          "Have a picnic with someone",
          "Have dinner with someone",
          "Go to an exhibition with someone",
          "Take a walk on a beach with someone",
          "Go cycling with someone",
          "Go to a local event with someone",
          "Go to cinema with someone",
          "Go to the zoo with someone",
          "go to an art exhibition with someone",
          "visit a local market with someone",
          "Go Bowling with someone",
          "Cook a meal with someone",
          "Eat ice cream with someone",
          "Sing karaoke with someone",
          "Create a funny video with someone",
          "Go shopping with someone",
          "Attend a live music gig with someone",
          "Inivite someone for brunch",
          "Read spooky stories together",
          "Make a playlist with someone",
          "Craft something together",
          "Go birdwatching together",
          "Tell each others fortune",
          "Dance with someone",
          "Try a new hobby together",
          "Go stargazing with someone",
          "Visit a viewpoint together",
          "Visit a bookstore together",
          "Have a game night with someone",
          "Visit a library together",
          "Go window shopping with someone",
          "Watch a documentary together",
          "Share a dessert",
          "Take photos together",
          "Visit a museum together",
          "Have a picnic breakfast with someone",
          "Try a new snack together",
          "Explore a park together",
          "Do a puzzle together",
          "Take a train ride together"
        ]
      },
      {
        "key": "encounter",
        "label": "Encounter",
        "shape": "encounter",
        "quests": [
          "Recommend a song to a friend",
          "Give someone a compliment",
          "Take a selfie with another person",
          "Call a friend",
          "Say thank you in person",
          "Share a joke",
          "Do a favor for someone",
          "Ask for a song recommendation",
          "Call a family member",
          "Recommend a TV show to someone",
          "Recommend a dish to someone",
          "Recommend a movie to someone",
          "Give a stranger a compliment",
          "Give a stranger a gift",
          "Give your friend a gift",
          "Hug a friend",
          "Write someone a poem",
          "Write someone a letter",
          "Ask someone about their day",
          "Tell someone about your day",
          "Find out something new about soemone",
          "Recommend someone a book",
          "Compliment someones outfit",
          "Ask someone for a family recipe",
          "recite a poem to someone",
          "Make someone smile",
          "Make someone laugh",
          "Surprise someone",
          "Smile at a stranger",
          "Ask someone about their favorite movie",
          "Thank a worker",
          "Start a short conversation",
          "Send a postcard",
          "Ask someone how their day is going",
          "Recommend a book",
          "Share a fun fact",
          "Tell someone a funny story",
          "Introduce two people",
          "Ask for a local recommendation",
          "Write a thank-you note",
          "Compliment someone's work",
          "Share a photo with a friend",
          "Wish someone a good day",
          "Offer help carrying something",
          "Ask someone about a hobby",
          "Teach someone a small skill",
          "write someone a letter/postcard"
        ]
      }
    ]
  }
};
